### ISSUE TITLE
Set up PPA for rr and build deps

### ISSUE THREAD

**Issue by joneschrisg** [rr-debugger/rr#26]
This will greatly simplify the setup process.  The only snag is that the libpfm build system is kind of a PITA, so getting cross-compiled libs built may be an issue.

**Comment by garrison** [comment]
Just wanted to check here to make sure there is still no PPA for rr, correct?  We are toying with the idea of running julia's travis-ci builds under rr, and a PPA would help greatly with that.

**Comment by cgjones** [comment]
That's correct, no PPA yet.  As a "workaround", rr is currently included with debian unstable and ubuntu 15.04, so it might be possible to install rr from a link to the right repo.  Also, the latest rr release package is always available per instructions here [here](http://rr-project.org/) (which should be installable in the travis-ci environment).

**Comment by garrison** [comment]
Thanks!  I will play around with this.

**Comment by luser** [comment]
I looked into this for something once and for an actual PPA you have to upload source packages to Launchpad and they build your binaries for you. Alternately we could just sort out hosting our own apt source and let users do that. That's the solution Jenkins uses:
https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu

We'd have to sign our .debs, but that's probably a good thing in any event.

**Comment by GitMensch** [comment]
nowadays rr is packed in a lot of distributions and the [build instructions](https://github.com/rr-debugger/rr/wiki/Building-And-Installing) should help otherwise.

I _think_ nowadays an appimage created as an artifact would be more interesting.
Side note: the CI does [provide a binary artifact for android x86_64 since 9 months](https://github.com/rr-debugger/rr/commit/ad46ca70ef55d89dc129704b2229064456f18f6e) (the dependencies would need to be installed separately), the same could be done for GNU/Linux, too (but a full appimage containing the dependencies would obviously be much more useful).

**Comment by rocallahan** [comment]
Yeah I don't think we need this
