### ISSUE TITLE
Incomplete read() when reading from stdin

### ISSUE THREAD

**Issue by altmannmarcelo** [rr-debugger/rr#2795]
Hi there, while trying to use rr with Percona Xtradb Cluster I've found out that rr is not working when it has to read some data from a file descriptor. It's only able to read the first 128KB from it.

Some env information:
``` 
rr --version
rr version 5.4.0

git log -n 1
commit 2faee91c531ebdb54cdf6fa8b6c2af45cc0edd7e (HEAD -> master, origin/master, origin/HEAD)

uname -a
Linux marce-bld 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

marcelo@marce-bld:/work/rr$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
``` 

I've create a small program to reproduce the issue:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
int main() {
  int fd, sz;
  int count = 1 * 1024 * 1024 * 1024;
  char *buf = (char *)calloc(count, sizeof(char));
  fd = 0;

  for (;;) {
    sz = read(fd, buf, count);
    if (sz != static_cast<int64_t>(count)) {
      printf("called read(% d, c, % d).  returned that"
             " %d bytes  were read.\n",
             fd, count, sz);
      if (sz == -1) {
        printf("Error reading file\n");
        return -1;
      } else if (sz != 0) {
        buf += sz;
        count -= sz;
      } else {
        buf[sz] = '\0';
        break;
      }
    }
  }
  return 0;
}
```

* Compile:
```
g++ -g -o read read.cc
``` 

* Create a 1M file
```
dd if=/dev/urandom of=sample.txt bs=1M count=1
```

* Make a bash script to cat the file and send it to read program
``` 
cat <<EOF > run.sh
#!/bin/bash
cat sample.txt | ./read
EOF

chmod +x run.sh
```

* Running `run.sh` without rr:
```
./run.sh 
called read( 0, c,  1073741824).  returned that 65536 bytes  were read.
called read( 0, c,  1073676288).  returned that 65536 bytes  were read.
called read( 0, c,  1073610752).  returned that 65536 bytes  were read.
called read( 0, c,  1073545216).  returned that 65536 bytes  were read.
called read( 0, c,  1073479680).  returned that 65536 bytes  were read.
called read( 0, c,  1073414144).  returned that 65536 bytes  were read.
called read( 0, c,  1073348608).  returned that 65536 bytes  were read.
called read( 0, c,  1073283072).  returned that 65536 bytes  were read.
called read( 0, c,  1073217536).  returned that 65536 bytes  were read.
called read( 0, c,  1073152000).  returned that 65536 bytes  were read.
called read( 0, c,  1073086464).  returned that 65536 bytes  were read.
called read( 0, c,  1073020928).  returned that 65536 bytes  were read.
called read( 0, c,  1072955392).  returned that 65536 bytes  were read.
called read( 0, c,  1072889856).  returned that 65536 bytes  were read.
called read( 0, c,  1072824320).  returned that 65536 bytes  were read.
called read( 0, c,  1072758784).  returned that 65536 bytes  were read.
called read( 0, c,  1072693248).  returned that 0 bytes  were read.
``` 

* Running `run.sh` with rr:
``` 
rr ./run.sh 
rr: Saving execution to trace directory `/home/marcelo/.local/share/rr/run.sh-4'.
called read( 0, c,  1073741824).  returned that 65536 bytes  were read.
called read( 0, c,  1073676288).  returned that 65536 bytes  were read.
``` 
only the first 128K are read and the program stalls.

**Comment by rocallahan** [comment]
`cat` writes 64K to the pipe, then the second write stalls because we've filled the default pipe size:
```
{
  real_time:2070924.967873 global_time:745, event:`SYSCALLBUF_FLUSH' tid:890569, ticks:107364
  { syscall:'write', ret:0x10000, size:0x10, desched:1 }
}
{
  real_time:2070924.967878 global_time:746, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:890569, ticks:107364
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x10000 rsi:0x7f7f05818000 rdi:0x1 rbp:0x1 rsp:0x681ffe20 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12
:0x7f7f0551003e r13:0x7f7f0551002e r14:0x7f7f05818000 r15:0x10000 rip:0x7000000e eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base
:0x7f7f05610b80 gs_base:0x0
}
```

Then `read` reads two 64K chunks. I guess after reading the first chunk the kernel wakes up and is able to get the data produced by the second write by `cat`. Naturally, `read` then stalls because the pipe is empty.

At this point `cat`'s blocked write should complete and `cat` should resume. For some reason it does not.

**Comment by rocallahan** [comment]
Ah, it's because of this:
```
[WARN done_preparing_internal()] `read' needed a scratch buffer of size 1073610752, but only 2093056 was available.  Disabling context switching: deadlock may follow.
```

**Comment by rocallahan** [comment]
We disable context switching to prevent another thread from reading the output buffer while the kernel is writing to it (i.e. a data race). Obviously in this case this leads immediately to a deadlock.

One option to fix this would be to simply stop doing this context switching and allow the potential data race. A correct program should not have such a data race. Of course, we want rr to work with incorrect programs.

Another option would be to avoid disabling context switching under some conditions, e.g. when we are sure such a data race cannot occur. In this case it cannot occur because there is no other thread that can read or write to `read`'s input buffer. This particular fix would probably be overly fragile, e.g. it would fail if `read` happened to have more than one thread.

**Comment by rocallahan** [comment]
There might be some solution that breaks up a large `read()` syscall into many small ones that individually fit into the scratch buffer. That sounds a bit scary since we'd potentially break atomicity guarantees, e.g. if some application sets the pipe buffer size higher than our scratch buffer size (2MB).

Another possible approach might be to detect the deadlock and break it. E.g. if the blocking `read()` syscall goes on too long we could reenable context switching and do a context switch. One problem with this approach is that it could make recording very slow if this occurs repeatedly in a recording.

**Comment by rocallahan** [comment]
I'm leaning towards just disabling context switching and allowing the race, but I'm not very sure about it.
