### ISSUE TITLE
Does not compile on aarch64 fedora

### ISSUE THREAD

**Issue by qiujiangkun** [rr-debugger/rr#2824]
Version 5.4.0 c287873
```log
/home/fedora/rr/src/test/reverse_step_threads_break.c: In function ‘my_read’:
/home/fedora/rr/src/test/reverse_step_threads_break.c:25:2: error: #error define syscall here
   25 | #error define syscall here
      |  ^~~~~
/home/fedora/rr/src/test/reverse_step_threads_break.c:12:27: error: unused parameter ‘fd’ [-Werror=unused-parameter]
   12 | static size_t my_read(int fd, void* buf, size_t size) {
      |                       ~~~~^~
/home/fedora/rr/src/test/reverse_step_threads_break.c:12:37: error: unused parameter ‘buf’ [-Werror=unused-parameter]
   12 | static size_t my_read(int fd, void* buf, size_t size) {
      |                               ~~~~~~^~~
/home/fedora/rr/src/test/reverse_step_threads_break.c:12:49: error: unused parameter ‘size’ [-Werror=unused-parameter]
   12 | static size_t my_read(int fd, void* buf, size_t size) {
      |                                          ~~~~~~~^~~~
```

**Comment by wcohen** [comment]
Currently Fedora is only building it for x86_64 and i686. I did some investigation and there are a number of other places that have similar architecture specific ifdefs including reverse_step_threads_break.c.

a/src/preload/overrides.c
a/src/preload/raw_syscall.S
a/src/preload/syscall_hook.S
a/src/preload/syscallbuf.c
a/src/test/explicit_checkpoints.c
a/src/test/gdb_bogus_breakpoint.c
a/src/test/reverse_step_threads_break.c

**Comment by khuey** [comment]
We don't regularly build the aarch64 port because it's still highly experimental so it's not surprising that it has bitrotted a bit.

**Comment by wcohen** [comment]
@khuey any later known git commits where the aarch64 port build was sucessful?

**Comment by GitMensch** [comment]
@khuey created [a bunch of commits for aarch64](https://github.com/rr-debugger/rr/search?q=aarch64&type=commits) in June, including the one referenced here, so I _guess_ this may be already solved (otherwise at least the build should be quite fine).

**Comment by khuey** [comment]
The AArch64 build works on Ubuntu.

For Fedora somebody needs to change https://github.com/rr-debugger/rr/blob/da98f7684e381781ec4557835a6f6ecbc73488c0/CMakeLists.txt#L58 to find the LSE-enabled dynamic linker on Fedora in order for the build to work.

**Comment by wcohen** [comment]
The current rr git repo builds on aarch64 Fedora 34, but when trying to package up as a RPM the build fails during %install with

```
- Installing: /home/wcohen/rpmbuild/BUILDROOT/rr-5.4.0-2.fc34aarch64_git.aarch64/usr/lib64/rr/testsuite/obj/bin/test-monitor
CMake Error at aarch64-redhat-linux-gnu/cmake_install.cmake:2409 (file):
  file INSTALL cannot find
  "/home/wcohen/rpmbuild/BUILD/rr-5.4.0/aarch64-redhat-linux-gnu/bin/cpuid":
  No such file or directory.
```
Can see this on a scratch build using a tarball from git repo https://koji.fedoraproject.org/koji/taskinfo?taskID=71835185 and it's build.log, https://kojipkgs.fedoraproject.org//work/tasks/5185/71835185/build.log

**Comment by wcohen** [comment]
This is using the one from the fedora rr.spec from rr-5.4.0-2.fc34.src.rpm rather than the one in the git repository.  You can get this from https://koji.fedoraproject.org/koji/taskinfo?taskID=71835078

**Comment by khuey** [comment]
Try that.

**Comment by wcohen** [comment]
Success building rr rpms for aarch64. Needed remove rr_page_* from file lists when non-x86 otherwise get the following

```
Processing files: rr-5.4.0-2.fc34aarch64_git.aarch64
error: File not found: /home/wcohen/rpmbuild/BUILDROOT/rr-5.4.0-2.fc34aarch64_git.aarch64/usr/share/rr/rr_page_*


RPM build errors:
    File not found: /home/wcohen/rpmbuild/BUILDROOT/rr-5.4.0-2.fc34aarch64_git.aarch64/usr/share/rr/rr_page_*

```

**Comment by wcohen** [comment]
X86 has a very limited list of architectures where rr works.  Which aarch64 microarchitectures would be the best choices for running the testsuite on?

**Comment by khuey** [comment]
> 
> 
> Success building rr rpms for aarch64. Needed remove rr_page_* from file lists when non-x86 otherwise get the following
> 
> ```
> Processing files: rr-5.4.0-2.fc34aarch64_git.aarch64
> error: File not found: /home/wcohen/rpmbuild/BUILDROOT/rr-5.4.0-2.fc34aarch64_git.aarch64/usr/share/rr/rr_page_*
> 
> 
> RPM build errors:
>     File not found: /home/wcohen/rpmbuild/BUILDROOT/rr-5.4.0-2.fc34aarch64_git.aarch64/usr/share/rr/rr_page_*
> ```

There should be a librrpage.so in the final package. The `rr_page_xx` stuff is outdated (I think that's changed since 5.4).

**Comment by khuey** [comment]
> 
> 
> X86 has a very limited list of architectures where rr works. Which aarch64 microarchitectures would be the best choices for running the testsuite on?

Something that supports LSE atomics. The only thing I'm aware of that's widely accessible is the AWS Graviton 2.

**Comment by wcohen** [comment]
Yes, the `rr_page_xx` looks to be gone, so removed that from the rr.spec file list completely.

So ARMv8.1 or higher is required.  As a smoke test I tried things on my local armv8 board that doesn't have LSE support.  Would have expected  `rr` to print out something and then fail, but ended up getting:

```
$ /usr/bin/rr
-bash: /usr/bin/rr: No such file or directory
$ file /usr/bin/rr
/usr/bin/rr: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/aarch64-linux-gnu/atomics/ld-linux-aarch64.so.1, BuildID[sha1]=c02c7d8d851a5ab5d842ad27e301b47e6dd2077f, for GNU/Linux 3.7.0, stripped
```

**Comment by khuey** [comment]
Right, so the "file not found" there is actually the dynamic linker missing. As I said above the `-Wl,-dynamic-linker` option above needs to be replaced with a path that works on Fedora and presumably /lib/aarch64-linux-gnu/atomics/ld-linux-aarch64.so.1 doesn't.

On Debian/Ubuntu there's a libc6-lse which installs LSE versions of glibc/etc. The dynamic linker selects whether to load the "old" glibc or the LSE glibc based on the hwcaps at runtime. But the dynamic linker is loaded by the kernel itself from a location hardcoded into each ELF object on the system. libc6-lse does not replace the "old" dynamic linker with an LSE enabled dynamic linker, so the `-Wl,-dynamic-linker` option is necessary. It's not just rr itself that needs this, any program that you would want to record needs to use the LSE ld (and glibc, pthreads, and every other library too). The AArch64 rr is thus much more difficult to use right now than the x86 version because of this.

Ideally installing libc6-lse would *replace* the existing dynamic linker with an LSE enabled one. I don't know how Fedora has chosen to package things. If you do replace the existing linker with an LSE enabled version you can simply remove the -Wl,-dynamic-linker option entirely from the build and add a dependency on the libc6-lse equivalent package, otherwise you need to update the path there to point to the right place. Alternatively, using -moutline-atomics on ld would work too (and Ubuntu might move to this, see https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1933879).

The old-style atomic instructions are non-deterministic and thus fatal to rr, hence this unfortunate song and dance with the LSE binaries.

**Comment by bgamari** [comment]
@khuey are you sure that Debian has upstreamed the `libc6` packaging changes introducing the LSE build variant? I see no such change in the changelogs.

**Comment by khuey** [comment]
I believe Debian actually uses `-moutline-atomics` for libc so there's no need to ship a separate libc6-lse like Ubuntu does, but I'm going from memory here so don't hold me to that :)

**Comment by bgamari** [comment]
Indeed it looks like `-moutline-atomics` is used in `glibc-2.31-0experimental2` (13 July 2020) and later by virtue of using `gcc-10`, which evidently enables `-moutline-atomics` by default.

Thanks for the pointer @khuey!

**Comment by wcohen** [comment]
Yes, rr now builds on Fedora:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1898144
