### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by solson** [rr-debugger/rr#2915]
I'm not sure if this is the right place to ask this, but would it be possible to cut a new stable release of `rr` soon? I personally need [this unreleased commit](https://github.com/rr-debugger/rr/pull/2762/commits/854b51effa25c7be3d6687ac0d6ef8afe9b3e3bb) to use rr on a Ryzen 5900X.

**Comment by GitMensch** [comment]
As a workaround you may [build from master](https://github.com/rr-debugger/rr/wiki/Building-And-Installing). But as this includes installing a bunch of additional software (instead of just installing a rr-debugger from the package manager) this may not be possible for everyone.

.. I personally would need eb449986b5c9c1252ac47f4ce062c9f7b51f16f4 ...

**Comment by gtors** [comment]
I faced with this error message `[FATAL ../src/PerfCounters_x86.h:94:compute_cpu_microarch()] AMD CPU type 0x20f10 unknown`. 
I suppose it will be fixed after next release?

**Comment by solson** [comment]
@gtors Yep, that's fixed in the commit I linked to above and it would be included in the next release.

**Comment by GitMensch** [comment]
@gtors: to be clear: this is fixed already in the repo, if you build from master as noted above you can use rr already, otherwise you'd have to wait for both a release (it will be included _with_, not _after_ the release) and for whatever package manager you use to ship the new version (which can take quite some time, especially on "stable distributions" like Debian).

**Comment by khuey** [comment]
Yeah one reason we don't do "releases" very often is that distros/package managers don't pick them up very often and since our users are other programmers they can almost always build rr from source.

**Comment by GitMensch** [comment]
Ranting: It would be much more easy if `cmake` would not be a necessary tool to build the beast... but I get there is no way back...

**Comment by grooverdan** [comment]
@khuey, I was looking to expand your userbase to sysadmins/dbas by including rr in a container (https://quay.io/repository/mariadb-foundation/mariadb-debug) so that our users could capture needed information that is otherwise hard to replicate to the developers environment.

While I can of course manually build from source, a package would make this significantly easier. An aarch64 package/tarball at the same time would also be appreciated.

**Comment by khuey** [comment]
rr "works" on aarch64 with a list of caveats that make it unsuitable for most use at this point.

**Comment by khuey** [comment]
We did this a few days ago. 5.5.0 is out.
