### ISSUE TITLE
New `perf_event_mmap` test "fails" in no-syscallbuf mode.

### ISSUE THREAD

**Issue by bernhardu** [rr-debugger/rr#2975]
Today I tried running the test suite and found these tests failing with current git:
```
The following tests FAILED: (regular x86_64 build)
        1019 - perf_event_mmap-no-syscallbuf (Failed)
        2373 - perf_event_mmap-32-no-syscallbuf (Failed)

The following tests FAILED: (with force32bit)
        1019 - perf_event_mmap-no-syscallbuf (Failed)
```
This was with `Linux rechner 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`, Debian Bullseye, AMD Ryzen 7 1700.

I got similar results with my `Linux asus-x555ld 5.14.0-1-amd64 #1 SMP Debian 5.14.6-2 (2021-09-19) x86_64 GNU/Linux`, Debian Testing, i5-4210U, bare metal and qemu VM.

As far as I see these tests are expected to fail, but they don't on my systems - am I doing something wrong?

**Comment by bernhardu** [comment]
Is anyone seeing this too, or is this limited to my environment?

**Comment by khuey** [comment]
I see it too.

**Comment by khuey** [comment]
So the problem here is that this test just passes by accident. It's trying to test that we don't allow perf_event_open with mmaps. rr doesn't actually have any code to prevent that though. When running with syscallbuf enabled the desched_fd is open and it's blocked from being closed by a PreserveFileMonitor.  `Task::stat_fd` returns the same inode/device for both perf events and we think they're the same, and we die trying to install a MmappedFileMonitor on the internal fd that already has a PreserveFileMonitor.

```
khuey@minbar:~/dev/rr$ stat -L /proc/91224/fd/3
  File: /proc/91224/fd/3
  Size: 0               Blocks: 0          IO Block: 4096   weird file
Device: dh/13d  Inode: 14454       Links: 1
Access: (0600/?rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-11-28 08:33:41.152000000 -0800
Modify: 2021-11-28 08:33:41.152000000 -0800
Change: 2021-11-28 08:33:41.152000000 -0800
 Birth: -
khuey@minbar:~/dev/rr$ stat -L /proc/91224/fd/100
  File: /proc/91224/fd/100
  Size: 0               Blocks: 0          IO Block: 4096   weird file
Device: dh/13d  Inode: 14454       Links: 1
Access: (0600/?rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-11-28 08:33:41.152000000 -0800
Modify: 2021-11-28 08:33:41.152000000 -0800
Change: 2021-11-28 08:33:41.152000000 -0800
 Birth: -
```
