### ISSUE TITLE
Recording occasionally attempts to bind to non-existant CPU

### ISSUE THREAD

**Issue by mystor** [rr-debugger/rr#3175]
Recently I've been running into an intermittent situation where I get an error like:

```
pid:742072 [FATAL /home/nika/src/rr/rr/src/[Session.cc:758](http://session.cc:758/):do_bind_cpu() errno: EINVAL] Can't bind to requested CPU 68, and CPUID faulting not available
```

This appears to be being caused by rr selecting a CPU which is outside of the range of actually available CPUs on a Zen system. This machine only has 64 CPUs, so CPU 68 does not exist.

From looking into the source more it appears this is due to the logic in `get_cgroup_cpus`, which queries the `/proc` directory to read the `Cpus_allowed_list`, which on my system reports that CPUs which aren't physically present are allowed. Specifically:

```
$ cat /proc/cpuinfo | grep processor | wc -l
64
$ cat /proc/self/status | grep 'Cpus_allowed'
Cpus_allowed:   ffffffff,ffffffff,ffffffff,ffffffff
Cpus_allowed_list:      0-127
```

It may be necessary to perform an intersection check when reading `Cpus_allowed_list` to make sure that the CPU which we pick is actually present on the system before trying to set thread affinity, especially on zen where we CPUID faulting is not available.

**Comment by khuey** [comment]
This seems like it may be related to @rocallahan's recent changes around cgroups.

**Comment by rocallahan** [comment]
I think you mean @Keno's changes...

**Comment by khuey** [comment]
Maybe I do!

**Comment by Keno** [comment]
Yes, this is possible caused by my recent changes and is also somewhat related to #3122. It appears that some AMD CPUs declare themselves to have twice as many cores as they actually do, just with some of them offline. I saw the same behavior on AMD Van Gogh, though frankly it looked like a BIOS bug to me (which didn't seem that unlikely to me, since Van Gogh is a one-off SoC). I didn't realize it was more widespread issue.

**Comment by rocallahan** [comment]
I'm working on it...
