### ISSUE TITLE
`rr pack`'d traces seem to still reference local files

### ISSUE THREAD

**Issue by andreubotella** [rr-debugger/rr#3177]
I was trying to use `rr pack` for debugging the difference between two Chromium branches, by recording an execution of a unit test under each branch and doing `rr pack` so I could debug them side by side. However, when debugging the trace that doesn't correspond to the latest build, I get the following message:

```
warning: .dynamic section for "/path/to/chromium/src/out/Debug/libblink_core.so" is not at the expected address (wrong library or version mismatch?)
```

and when I try and do `p` to show a detailed print of a value, I get this:

```
(rr) p p1.ShowTreeForThis()

Thread 3 received signal SIGSEGV, Segmentation fault.
blink::PositionTemplate<blink::EditingAlgorithm<blink::NodeTraversal> >::ShowTreeForThis (this=0x562a8f294760) at ../../third_party/blink/renderer/core/editing/position.cc:702
702     void PositionTemplate<Strategy>::ShowTreeForThis() const {
The program being debugged was signaled while in a function called from GDB.
GDB has restored the context to what it was before the call.
To change this behavior use "set unwindonsignal off".
Evaluation of the expression containing the function
(blink::PositionTemplate<blink::EditingAlgorithm<blink::NodeTraversal> >::ShowTreeForThis() const) will be abandoned.
```

This segfault is not due to a change in the code because it happens consistently on branches which aren't the last one I've built, no matter which that is.

It's clear that `rr pack` did in fact run successfully because it returned error code 0, and because when replaying the traces, the binary being debugged is `~/.local/share/rr/blink_unittests-1/mmap_clone_4_blink_unittests`, rather than `/path/to/chromium/src/out/Debug/blink_unittests`.

**Comment by Keno** [comment]
You need to replay with --serve-files, otherwise gdb will try to lookup files on the local file system and might pick up the wrong things as a result.

**Comment by Keno** [comment]
It's a bit of a gotcha. I'm wondering if we should make `--serve-files` the default for packed traces. @rocallahan @khuey thoughts?

**Comment by rocallahan** [comment]
That makes sense to me.

**Comment by Hi-Angel** [comment]
Just stumbled upon the same problem and spent some time creating a testcase with containers, and then accidentally saw this issue. It is not "a bit of a gotcha", it is quite a large one. There is no documentation `rr pack --help` has no mention of the necessity of `--serve-files`, neither `rr replay --help` has. The `rr pack` is unusable without this option, because even the trivial `rr record true && rr pack` will break on you upon trying to replay it in a different environment.

@Keno I am looking at taking a stub at it, unless it's too complicated. Is there any way to tell that we are `replay`ing a `pack`ed directory? I tried looked at the diff before and after, and it's just these files:

```haskell
 mmap_pack_0_libpthread-2.27.so | Bin 0 -> 144976 bytes
 mmap_pack_1_libdl-2.27.so      | Bin 0 -> 14560 bytes
 mmap_pack_2_true               | Bin 0 -> 30904 bytes
 mmap_pack_3_librrpage.so       | Bin 0 -> 20480 bytes
 mmap_pack_4_ld-2.27.so         | Bin 0 -> 179152 bytes
 mmap_pack_5_librrpreload.so    | Bin 0 -> 479456 bytes
 mmap_pack_6_libc-2.27.so       | Bin 0 -> 2030928 bytes
 mmaps                          | Bin 869 -> 890 bytes
```
