### ISSUE TITLE
Running on a Mac

### ISSUE THREAD

**Issue by vjpr** [rr-debugger/rr#3331]
The readme says:

> rr currently requires either...Certain AArch64 microarchitectures (e.g. ARM Neoverse N1 or the Apple Silicon M-series)

It's not clear if there is a way to run on Apple hardware.

It would be great to clarify this, and to provide instructions on running from macOS. Is virtualization possible and how to setup the virtualization.

Related: https://github.com/rr-debugger/rr/issues/3234

Apple Intel with Windows Bootcamp via WSL 2: https://github.com/rr-debugger/rr/issues/2506

# Summary

- Apple Silicon macOS with Linux VM Guest Virtualization - **Nope**
- Apple Silicon Bare Metal (via Asahi Linux dist) - **Yep**
- Apple Silicon Bootcamp - **Nope - Bootcamp on Silicon not possible**
- Apple Intel macOS with Linux VM Guest Virtualization - **Only before Big Sur** 
  See: https://github.com/rr-debugger/rr/issues/2897
- Apple Intel Bare Metal (any dist) - **Should work**
- Apple Intel Bootcamp Windows (WSL 2) - **Nope**

**Comment by yuyichao** [comment]
> It would be great to clarify this, and to provide instructions on running from macOS. Is virtualization possible and how to setup the virtualization.

There's no macOS or much of virtualization involved. It requires linux running on bare metal apple silicon.

We can probably add a link to the [Asahi Linux wiki](https://github.com/AsahiLinux/docs/wiki) or [front page](https://asahilinux.org/). I don't think any more detailed instruction can/should be included since while it (asahi linux) is already very usable for end users, many details are still in flux and we should not host a potentially out-of-date document of another project.

**Comment by vjpr** [comment]
Does it work on Apple Intel via virtualization?

**Comment by yuyichao** [comment]
While those are Mac related questions, they are not related to apple silicon and I do not know the answers.

**Comment by khuey** [comment]
Apple hardware is fine, Apple software is not. You'll need to be running Linux on the bare metal or a pre-Big Sur MacOS with a Linux VMWare guest and appropriate VMWare configuration. I don't think anyone has tried Bootcamp and WSL, WSL hasn't worked until quite recently.

**Comment by GitMensch** [comment]
So ... "close as not planned"?

**Comment by rocallahan** [comment]
Yes, not planned.

**Comment by baiwfg2** [comment]
I downloaded rr-5.7.0-Linux-aarch64 and try to run it on ubuntu on mac qemu with `-cpu=host` enabled. But it shows:
```
$ ./rr-5.7.0-Linux-aarch64/bin/rr record ./a.out
[FATAL src/PerfCounters_aarch64.h:134:get_cpuinfo_sysfs()] Failed to read midr register from kernel
```

**Comment by glycerine** [comment]
Just fyi, these guys from google got a proof of principle of macOS record and replay (not using rr codebase, but rather using the Hypervisor.framework and their own rust code) working last year

https://nickgregory.me/post/2024/06/23/warpspeed/

https://github.com/kallsyms/warpspeed

https://www.youtube.com/watch?v=KYkHDQYJ6fg

Its incomplete, and does not build for me under the latest nightly rustc version, but apparently all the hard parts are figured out for recording and replaying on XNU/darwin. Lots of technical detail in the talk/blog links above.

**Comment by sfleiter** [comment]
> Just fyi, these guys from google got a proof of principle of macOS record and replay (not using rr codebase, but rather using the Hypervisor.framework and their own rust code) working last year

I looked at warpspeed and updated some dependencies to make it build the rust parts.
After installing protobuf building the keystone-engine failed since that requires an old CMake version.
Looking at the warpspeed [commits](https://github.com/kallsyms/warpspeed/commits/main/) and [issues](https://github.com/kallsyms/warpspeed/issues) the project is dead and there is still a lot to do to make this usable.

Looks like a dead end to me.

**Comment by sidkshatriya** [comment]
> Apple Silicon macOS with Linux VM Guest Virtualization - Nope

Actually this is a "yes". You can run `rr` in a Linux VM on macOS apple silicon using https://github.com/sidkshatriya/rr.soft . `rr.soft` is a modification to `rr` to allow it to run without requiring hardware performance counters. (I built rr.soft)
