### ISSUE TITLE
Use of `extra_regs()` in ptrace emulation may be unsound

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3725]
Consider e.g. PTRACE_GETREGSET for NT_X86_XSTATE.

The code calls `verify_ptrace_target()` for the tracee task and then `extra_regs()` on that task. `verify_ptrace_target()` performs some checks of our internal state including that the tid is known to rr and the emulated ptracer is correct. It does not, however, check that the task still exists on the system (nor could it, since this is inherently racy). Using `extra_regs()` here seems like it always risks dying with `ESRCH` if we race with the process exiting. Am I missing something?

Cc @dbaron

**Comment by rocallahan** [comment]
Yeah I think all uses of `extra_regs()` during recording need to be replaced with `extra_regs_fallible()`.

**Comment by rocallahan** [comment]
Alternatively, we could treat extra_regs the same way we treat regs --- try to fetch them in `Task::did_waitpid`, and if we can't, pretend the current notification didn't happen because the task is dead. That would mean an extra syscall at every stop to fetch those registers, but that's probably OK.
