### ISSUE TITLE
Is there a way to use rr without recording?

### ISSUE THREAD

**Issue by sogartar** [rr-debugger/rr#3738]
I want to run my application with rr's [chaos mode](https://robert.ocallahan.org/2016/02/introducing-rr-chaos-mode.html). I am interested in using this thread scheduler to search for concurrency issues. The problem I have is that my application uses a GPU extensively and rr does not work with [such applications](https://github.com/rr-debugger/rr/issues/2173).

If the source of trouble is the recording interaction with the GPU, could I just not record but execute the application with rr to utilize its thread scheduler?

**Comment by rocallahan** [comment]
rr does not support that. Disentangling the parts you need from the recording machinery you don't want would be quite a lot of work and not all that useful since you wouldn't have a good way to debug any bugs you find that way.

It would probably make more sense to start from scratch and write a ptrace-based supervisor that uses the same principles as rr's chaos mode. You could even support multiple cores.
